export const CLASE_ACTIVADA = "CLASE_ACTIVADA";
export const CLASE_DESACTIVADA = "CLASE_DESACTIVADA";
export const REINICIAR_CLASE = "REINICIAR_CLASE";
export const MOSTRAR_ANIMACION = "MOSTRAR_ANIMACION";
export const MOSTRAR_ANIMACION_SCROLL = "MOSTRAR_ANIMACION_SCROLL";
export const REINICIAR_TODO = "REINICIAR_TODO";
